settings:
  title: 'єСвітло'
  url: 'https://13.malitov.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Світло є!'
  notAllmonitorsOperational: 'Є проблеми зі світлом!'
  monitorLabelOperational: 'Світло є'
  monitorLabelNotOperational: 'Без світла'
  monitorLabelNoData: 'Відсутні дані'
  dayInHistogramNoData: 'Відсутні дані'
  dayInHistogramOperational: 'Все ок'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: 13op # unique identifier
    name: 13 секція
    url: 'http://op13.malitov.com' # URL to fetch
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
